/** Use 3 — systematic narrative discovery + the macro-chain denominator. Writes tests/q3/discovery/YYYY-MM-DD.json and appends PENDING rows to tests/q3/macro-chain-log.json.
 *  Pool CANDIDATES come from Surf (discovery); the pool that enters a record must be confirmed venue-direct / Dune (v1.4 rule 1). 4 credits per market search, 1 per news search. */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { surf, CFG, journalCredits } from "./surf";
const today = new Date().toISOString().slice(0, 10); const args = process.argv.slice(2); const platforms = args.includes("--kalshi-only") ? ["kalshi"] : args.includes("--polymarket-only") ? ["polymarket"] : ["kalshi", "polymarket"];
const out: any = { date: today, pool_candidates: {}, news: [], macro_chain_hits: [] };
for (const p of platforms) { const seen = new Set<string>(); const rows: any[] = [];
  for (const cat of CFG.pool_categories) { try { const r = surf("search-prediction-market", ["--platform", p, "--category", cat, "--status", "active", "--sort-by", "volume_1d", "--limit", "5"]);
      for (const m of r.data) { const id = m.market_ticker ?? m.condition_id; if (seen.has(id)) continue; seen.add(id); rows.push({ id, category: m.category, question: m.question, volume_1d: m.volume_1d_usd ?? m.volume_1d ?? null, volume_7d: m.volume_7d_usd ?? m.volume_7d ?? null, oi: m.open_interest_usd, price: m.latest_price ?? null, days_to_resolution: m.days_to_resolution, link: m.market_link }); }
    } catch (e) { rows.push({ category: cat, error: (e as Error).message.slice(0, 120) }); } }
  out.pool_candidates[p] = rows.filter(r => !r.error).sort((x, y) => (y.volume_1d ?? y.volume_7d ?? 0) - (x.volume_1d ?? x.volume_7d ?? 0)).slice(0, 10); out.pool_candidates[p + "_errors"] = rows.filter(r => r.error); }
for (const q of CFG.macro_chain_queries) { try { const r = surf("search-news", ["--q", q, "--limit", "5"]); for (const n of r.data) { const pub = new Date(n.published_at * 1000).toISOString(); if (Date.now() - n.published_at * 1000 > 2 * 86400e3) continue; out.news.push({ q, title: n.title, url: n.url, source: n.source, published_at: pub, summary: n.summary?.slice(0, 200) }); if (/bitcoin|crypto|btc/i.test(n.title + " " + (n.summary ?? ""))) out.macro_chain_hits.push({ found: today, q, title: n.title, url: n.url, published_at: pub, outcome: "PENDING — operator marks HELD | BROKE | PARTIAL at horizon" }); } } catch (e) { out.news.push({ q, error: (e as Error).message.slice(0, 120) }); } }
mkdirSync("tests/q3/discovery", { recursive: true }); writeFileSync(`tests/q3/discovery/${today}.json`, JSON.stringify(out, null, 2) + "\n");
const mcl = "tests/q3/macro-chain-log.json"; const log = existsSync(mcl) ? JSON.parse(readFileSync(mcl, "utf8")) : { _comment: "Every macro→crypto chain narrative found, BOTH outcomes — the denominator for the class base rate. Operator fills outcome at horizon.", instances: [] };
const known = new Set(log.instances.map((i: any) => i.url)); for (const h of out.macro_chain_hits) if (!known.has(h.url)) log.instances.push(h); writeFileSync(mcl, JSON.stringify(log, null, 2) + "\n");
const used = journalCredits("discover", `${platforms.join("+")} · ${out.news.length} news · ${out.macro_chain_hits.length} chain hits`);
for (const p of platforms) { console.log(`POOL CANDIDATES · ${p} (v1.5 categories: ${CFG.pool_categories.join(", ")})`); for (const r of out.pool_candidates[p].slice(0, 5)) console.log(`  ${String(r.id).padEnd(34)} ${String(r.category).padEnd(10)} vol1d ${r.volume_1d ?? "?"}  oi ${Math.round(r.oi ?? 0)}  p ${r.price ?? "?"}  ${r.question?.slice(0, 60)}`); if (out.pool_candidates[p + "_errors"].length) console.log(`  errors: ${out.pool_candidates[p + "_errors"].map((e: any) => e.category + ": " + e.error).join(" | ")}`); }
console.log(`NEWS (48h) ${out.news.length} · MACRO-CHAIN HITS ${out.macro_chain_hits.length} → macro-chain-log.json (${log.instances.length} total, denominator)\n→ tests/q3/discovery/${today}.json · credits today ${used}/${CFG.credit_ceiling_per_day}`);
