/** Use 5 — Gate 2 mechanics for the audit-gate skill. MECHANICS ONLY: liquidation, buffers, R:R, funding cost. Says nothing about whether the thesis is sound — that is Gate 1 (the engine).
 *  npx tsx tests/q3/tape/gate2-mechanics.ts --pair BTC/USDT --side short --entry 77481.55 --notional 3000 --leverage 10 --stop 79800 --tp 73000 [--mmr 0.005] [--exchange binance] */
import { surf, CFG, pct } from "./surf";
const a = process.argv.slice(2); const flag = (f: string, d?: string) => { const i = a.indexOf(f); return i >= 0 ? a[i + 1] : d; };
const pair = flag("--pair", `BTC/${CFG.perp_reference.quote}`)!, ex = flag("--exchange", CFG.perp_reference.exchange)!, side = flag("--side")!.toLowerCase(), entry = Number(flag("--entry")), notional = Number(flag("--notional")), lev = Number(flag("--leverage")), stop = Number(flag("--stop")), tp = flag("--tp") ? Number(flag("--tp")) : NaN, mmr = Number(flag("--mmr", "0.005"));
if (!["long", "short"].includes(side) || ![entry, notional, lev, stop].every(Number.isFinite)) { console.error("need --side long|short --entry --notional --leverage --stop"); process.exit(1); }
const snap = surf("exchange-perp", ["--exchange", ex, "--pair", pair]); const d = Array.isArray(snap.data) ? snap.data[0] : snap.data; const f = d.funding ?? {}; const mark = f.mark_price ?? f.index_price ?? d.mark_price ?? null;
const dir = side === "long" ? 1 : -1; const size = notional / entry; const margin = notional / lev;
const liq = side === "long" ? entry * (1 - 1 / lev + mmr) : entry * (1 + 1 / lev - mmr);
const stopAdverse = dir * (stop - entry) < 0; const lossAtStop = Math.abs(stop - entry) * size; const gainAtTp = Number.isFinite(tp) ? Math.abs(tp - entry) * size : NaN;
const bufferStopToLiq = Math.abs(liq - stop) / stop; const rr = Number.isFinite(gainAtTp) ? gainAtTp / lossAtStop : NaN;
const f8 = f.funding_rate_8h ?? f.funding_rate ?? null; const fundPer8h = f8 != null ? -dir * f8 * notional : null; // longs pay positive funding
const out = { pair, exchange: ex, side, entry, mark, mark_vs_entry: mark ? pct(mark / entry - 1) : null, size_base: +size.toFixed(6), initial_margin_usd: +margin.toFixed(2), liquidation_price: +liq.toFixed(2), stop, stop_is_adverse: stopAdverse, stop_to_liq_buffer: pct(bufferStopToLiq), max_loss_at_stop_usd: +lossAtStop.toFixed(2), max_loss_pct_of_margin: pct(lossAtStop / margin), take_profit: Number.isFinite(tp) ? tp : null, target_profit_usd: Number.isFinite(gainAtTp) ? +gainAtTp.toFixed(2) : null, rr: Number.isFinite(rr) ? +rr.toFixed(2) : null, funding_8h_rate: f8, funding_annualized: f.funding_annualized ?? f.funding_rate_annualized ?? null, funding_usd_per_8h: fundPer8h != null ? +fundPer8h.toFixed(2) : null, funding_usd_per_day: fundPer8h != null ? +(fundPer8h * 3).toFixed(2) : null, funding_direction: fundPer8h == null ? null : fundPer8h >= 0 ? `${side} RECEIVES` : `${side} PAYS`, open_interest_usd: d.open_interest?.open_interest_usd ?? d.open_interest_usd ?? null, mmr_assumed: mmr, next_funding: f.next_funding ?? null };
const flags: string[] = []; if (!stopAdverse) flags.push("stop is on the profit side of entry — not a stop"); if (bufferStopToLiq < 0.05) flags.push(`stop→liquidation buffer ${pct(bufferStopToLiq)} < 5% — a wick through the stop can liquidate`); if (lossAtStop / margin > 0.5) flags.push(`stop risks ${pct(lossAtStop / margin)} of margin`); if (Number.isFinite(rr) && rr < 1.5) flags.push(`R:R ${rr.toFixed(2)} < 1.5`); if (mark && Math.abs(mark / entry - 1) > 0.01) flags.push(`entry is ${pct(entry / mark - 1)} from current mark — stale entry`);
console.log(`GATE 2 · MECHANICS ONLY — this is not a verdict on the thesis. Gate 1 (the engine) decides whether a reason exists.\n${JSON.stringify(out, null, 2)}\nFLAGS: ${flags.length ? "\n  - " + flags.join("\n  - ") : "none"}\nliquidation uses isolated-margin approximation with mmr=${mmr}; confirm against the venue's tier table before relying on it.`);
